### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by devmondo** [aurelia/logging#13]
right now i get an error like this

Unhandled promise rejection Error: Lexer Error: Unexpected character [#] at column 0 in expression [#]
    at Scanner.error (http://localhost:9500/jspm_packages/github/aurelia/binding@0.8.5/aurelia-binding.js:2408:13)
 

and when you have lots and lots of custom elements, attributes, etc... it is very hard to find out the source of the problem, so i do manual work by disabling them one by one, and it even gets wors when you have dynamic injection of those element, 

could there be a way for the message to say which file is causing the issue ?

thanks in advanced.

**Comment by EisenbergEffect** [comment]
This isn't an issue with the logging library. That said, we now have the view-spy and compile-spy to assist in this issue.
