### ISSUE TITLE
incorrect TypeScript typings, missing ...rest:any[] in method signatures

### ISSUE THREAD

**Issue by migajek** [aurelia/logging#16]
The signatures of ``debug, info, warn, error`` methods should contain second parameter ``..rest: any[]`` to match it's actual behavior

**Comment by JeroenVinke** [comment]
yes, sounds like the parameter is lost in the dts generator

[this](https://github.com/aurelia/logging/blob/master/src/index.js#L100) gets translated to [this](https://github.com/aurelia/logging/blob/master/dist/aurelia-logging.d.ts#L7)

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you take a look into this and see if there's a bug in our d.ts generator?

**Comment by cmichaelgraham** [comment]
@EisenbergEffect @JeroenVinke @migajek @Alxandr - i will look into this tonight :+1:

**Comment by cmichaelgraham** [comment]
got it - two properties for interface methods: `params` and `rest`.  now i just have to figure out how to stitch it together, but that will have to wait for tomorrow.  the 1st two errors were a simple fix.  that's in the branch already

**Comment by cmichaelgraham** [comment]
all tests passing !!! :) :)

```
$ npm test

> babel-dts-generator@0.2.14 test c:\a\cmg\babel-dts-generator
> node node_modules/mimosa/bin/mimosa build & node lib/test.js

14:50:57 - Info - Beginning build
14:50:58 - Success - Deleted file lib\index.js
14:50:58 - Success - Deleted file lib\test.js
14:50:59 - Success - Wrote file lib\test.js
14:50:59 - Success - Wrote file lib\index.js
14:50:59 - Success - Finished build
Success: spec/class/method.src.js
Success: spec/parameters/restparm-class-resttyped.src.js
Success: spec/parameters/restparm-class-restuntyped.src.js
Success: spec/parameters/restparm-function-resttyped.src.js
Success: spec/parameters/restparm-function-restuntyped.src.js
Success: spec/parameters/restparm-interface-resttyped.src.js
Success: spec/parameters/restparmonly-class-resttyped.src.js
Success: spec/parameters/restparmonly-class-restuntyped.src.js
Success: spec/parameters/restparmonly-function-resttyped.src.js
Success: spec/parameters/restparmonly-function-restuntyped.src.js
Success: spec/parameters/restparmonly-interface-resttyped.src.js
Success: spec/var.src.js
```

Next: clean-up, commit, PR, deploy, rebuild, rerelease, and voila :+1:

**Comment by cmichaelgraham** [comment]
[babel-dts-generator npm package](https://www.npmjs.com/package/babel-dts-generator) published with `...rest` parameter support :+1:
