### ISSUE TITLE
support loglevel on individual logger instances

### ISSUE THREAD

**Issue by ghost** [aurelia/logging#18]
Allow `logLevel` to be set for each specific logger. This way we could selectively increase/decrease/disable logging for a specific noisy source without turning it off for the rest.

Perhaps the global `setLevel` could be used as a convenience method to set a level across all loggers?

**Comment by EisenbergEffect** [comment]
@shawnExplore That's a great idea. I can tell you we won't have time on our core team to address this for our v1 release. It could happen in a point release thereafter though. If you would like to see this sooner, then we could accept a PR for this feature. It's important to take into consideration that adding this feature should not cause any breaking changes to the API or behavior though. So, please keep that in mind if you want to take this on.

**Comment by shawnExplore** [comment]
I tried to change the existing code minimally - to avoid breaking changes per your comment. All the original tests pass without modification.

**Comment by EisenbergEffect** [comment]
That's a good sign. I check it out soon. Thank you for being so willing to contribute!!!

**Comment by EisenbergEffect** [comment]
@ghost Did you have any interest in submitting the PR?

**Comment by EisenbergEffect** [comment]
@ShawnTalbert Did you have any interest in submitting an updated PR?

**Comment by ShawnTalbert** [comment]
Yes. Sorry that other projects have consumed me the last few months.

**Comment by ShawnTalbert** [comment]
Apparently @ghost is what github did to my old username when I deleted it in favor of this one.

**Comment by ShawnTalbert** [comment]
@EisenbergEffect if this were merged I could stop using my private fork  :)

**Comment by EisenbergEffect** [comment]
Will review shortly. Before I review, this doesn't make any breaking changes, correct? It just adds a new feature, right?

**Comment by ShawnTalbert** [comment]
Yes, the goal was to push the previously global `logLevel` down to individual instances. 

I also tried to preserve the original behavior (and all the original tests still pass FWIW). Specifically,  the top level `setLevel()` function now sets the level on _all_ registered loggers which simulates the previous approach where that log level variable was shared among loggers. 

I do admit I'm using individual logLevels most of the time; less so with the top-level `setLevel()`.

**Comment by ShawnTalbert** [comment]
I really do need this feature, but will admit also that I'm using this library predominately _outside_ Aurelia apps. (Kudos for no Aurelia dependencies).

I intend to use it in Aurelia apps as well, especially as those apps get more complex.

**Comment by EisenbergEffect** [comment]
I will review soon.

**Comment by Thanood** [comment]
It appears this change is in.. :smiley: 

I just noticed that at the time `use.developmentLogging()` only three loggers are configured to log at all:
* `aurelia`
* `property-observation`
* `templating`

![image](https://cloud.githubusercontent.com/assets/677826/19441631/9b03d7c2-9486-11e6-8ef8-f6b5422632fb.png)

Because all other loggers deault to logLevel `none` I'm only seeing these threee loggers.
I guess that this side-effect is not intended.

I propose to carry a `globalDefaultLevel` in the LogManager with which all created loggers are initialized.

IMO that should fullfil this proposal:
> the goal was to push the previously global logLevel down to individual instances.

**Comment by EisenbergEffect** [comment]
Oop! Yes. Can you submit a PR for that? If so, we can get it released pretty quickly.

**Comment by Thanood** [comment]
Please see #26..
I hope the test is sufficient. :smiley:
