### ISSUE TITLE
Logger methods should take multiple arguments?

### ISSUE THREAD

**Issue by ghost** [aurelia/logging#20]
I just finally realized that the `Appender.debug` interface is much more flexible than the `Logger.debug` interface.

`Logger.debug()` accepts only a single string parameter, whereas the `Appender` is capable of supporting multiple parameters. The way it stands, I don't see how `Appender.debug()` will ever see anything more than a single string parameter if used via well-behaved (type honoring) `Logger`s?

I need this variadic function behavior supported at the Logger interface level (In my specific use case I have a custom appender that uses a log  **title:string** and **details:string** for each log message (two params) and end users should be able to specify both a title and a string through the Logger interface)

Am I missing something here or must we redefine Logger to accept variable params on the main debug,info,warn,error methods?

**Comment by EisenbergEffect** [comment]
We just need to fix up the typing. Would you be interested to submit a PR to make that correction?

**Comment by obany** [comment]
#22 Link To PR

**Comment by EisenbergEffect** [comment]
Merged PR. Thanks!
