### ISSUE TITLE
Missing TypeScript declaration file in npm package 1.0.0-beta.2.0.0

### ISSUE THREAD

**Issue by Costo** [aurelia/logging#21]
Hi,  
When installing the lastest npm package (1.0.0-beta.2.0.0) with jspm, the file `aurelia-logging.d.ts` is missing.  
I used the d.ts file found in this repository, but it is missing the module declaration (`declare module `aurelia-logging`) so I had to add it.  
Is there an issue with the package or am I missing something?

**Comment by StrahilKazlachev** [comment]
Info [here](http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/).
