### ISSUE TITLE
Can we handle LogLevel more elegantly?

### ISSUE THREAD

**Issue by ShawnTalbert** [aurelia/logging#28]
**I'm submitting a feature request**
- **Library Version:**
  1.1.0
- **Language:**
  TypeScript 2.0.3

**Desired Behavior**
This is a request to improve `LogLevel` definition and usage for TS users. I don't know flowtype well enough to offer a solution, hence this request.

In TypeScript, LogLevel could be defined and used in a straightforward manner:

``` typescript
enum LogLevel { none=0, debug=1, info=2, warn=3, error=4 }

//the signature of setLevel() could be strong typed instead of just 'number'
function setLevel(level:LogLevel) {}

setLevel( LogLevel.debug )
```

Currently, LogLevel _feels_ like it wants to be an enumeration, but as far as I could see flowtype doesn't have an easy answer that would result in the strong-typed ease of use in TypeScript as shown above. I tried a couple things but it appears the (babel?) processing of flowtype doesn't support flowtype disjoint union definitions.

This is my ask for someone smarter than me to figure out a way to make the logger work more like my example above. A handwritten `.d.ts` file could do it, but I know y'all use some magical `.d.ts` generator.

**Current Behavior**
For reference, currently `setLevel()` just takes a plain number, even though the expectation is that only values from the `LogLevel` enum should be arguments to this method. The signature doesn't guide the user and one just has to _know_  you should feed values from a predefined javascript object (e.g. `LogManager.logLevel.debug`).

**Comment by EisenbergEffect** [comment]
I think we can probably fix this. We are working on a setup which we can use to start porting various libraries to TypeScript. This is a small library so it's probably a good candidate for a first port.

**Comment by EisenbergEffect** [comment]
@jdanyow What do you think about trying this out after the validation library is sorted out? Switching the log level to a TS enum wouldn't cause a breaking change would it?

**Comment by ShawnTalbert** [comment]
Any progress here? Perhaps more interesting, are you porting other parts of Aurelia to TS?

**Comment by EisenbergEffect** [comment]
We are moving libs over to TS, one by one. If you are interested in helping we would appreciate that type of contribution.

**Comment by EisenbergEffect** [comment]
We are trying to prevent breaking changes, I should mention.

**Comment by balupton** [comment]
fwiw, https://github.com/bevry/caterpillar may be of interest to you, we've used it in DocPad for years and it has been really nice - extensible, RFC log based, streams based, already uses strong typing through flow type, but happy to redo it in TypeScript if you'd like.

**Comment by ShawnTalbert** [comment]
@EisenbergEffect I'm happy to help. but it's more complicated than just converting this library to TS. Since it's part of Aurelia, I assume it has to fit into the Aurelia build toolchain. Is there a standard for this established for the framework as a whole?

@balupton Thanks - will take a look!

**Comment by EisenbergEffect** [comment]
@jdanyow has been working on this. He may be able to comment and point you in the right direction.

**Comment by Alexander-Taran** [comment]
I think it is kinda addressed 
https://github.com/aurelia/logging/blob/300e74fe3a4e44613b7e2060b75fa012f9e5fe69/src/index.js#L35
