### ISSUE TITLE
Silent failures when there is no <template> wrapper since 1.1.0

### ISSUE THREAD

**Issue by fracz** [aurelia/logging#29]
**I'm submitting a bug report**
* **Library Version:**
1.1.0

When there is no `<template> ... </template>` wrapper in the view, Aurelia should fail with the following error:

> Template markup must be wrapped in a element e.g. <template>  </template>

It works, when using `aurelia-logging` in `1.0.0`. Updating to `1.1.0` breaks this (i.e. no error is shown).

See [SO question](http://stackoverflow.com/questions/40186564/aurelia-silently-fails-when-there-is-no-template-wrapper) regarding this.

**How to reproduce?**

* Clone [sekeleton-typescript](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript)
* Remove the `<template>` wrapper from `src/users.html`.
* Run `gulp serve` and try to enter the *Github users* subpage - this results in error in console (correct).
* Run `jspm update` - this will update `aurelia-logging` from `1.0.0` to `1.1.0`
* Run `gulp serve` and try to enter the *Github users* subpage - no error now

`jspm update` actually updates more than `aurelia-logging` for the skeleton. However, I have tracked the problem down to the `aurelia-logging` upgrade.

**Comment by EisenbergEffect** [comment]
We've got a fix in already. Just need to release it. Sorry for the regression!
