### ISSUE TITLE
Allow a Marker with Log Messages

### ISSUE THREAD

**Issue by RapidTransit** [aurelia/logging#34]
**I'm submitting a feature request**

**Current behavior:**

Log calls can only accept a String and additional Objects, with no option for a Marker, so if I have two different Elements that I need to separate, I kind of break logging with static methods.

```typescript
@inject(Parent.of(ValidationController), "CheckoutStates")
export class AddressForm<T extends BaseAddressInfoForm> implements ComponentAttached, ComponentDetached, ComponentCreated {

  private LOG : Logger;

  @bindable shouldValidate: () => boolean;
  @bindable prefix : string;
  @bindable address : T;


  constructor(private validationController : ValidationController, public states : string[]) {}

  public created(owningView: View, myView: View): void {
    this.LOG = LogManager.getLogger(`AddressForm:${this.prefix}`);
  }

  public attached(): void {
    this.LOG.debug("Address form attached to DOM");
    this.validationController.addObject(this.address, this.getAddressRules());
  }
```

**Expected/desired behavior:**

```typescript
@inject(Parent.of(ValidationController), "CheckoutStates")
export class AddressForm<T extends BaseAddressInfoForm> implements ComponentAttached, ComponentDetached, ComponentCreated {

  private static LOG : Logger = LogManager.getLogger('AddressForm');
  private marker : Marker;
  @bindable shouldValidate: () => boolean;
  @bindable prefix : string;
  @bindable address : T;


  constructor(private validationController : ValidationController, public states : string[]) {}

  public created(owningView: View, myView: View): void {
    this.marker = new Marker(this.prefix);
  }

  public attached(): void {
    AddressForm.LOG.debug(this.marker, "Address form attached to DOM");
    this.validationController.addObject(this.address, this.getAddressRules());
  }
```
* **What is the expected behavior?**
Log the messages with an identifier

* **What is the motivation / use case for changing the behavior?**
If you are reusing the same elements some opinions on current best practice dictates that a log field should be private, static, and final

https://logging.apache.org/log4j/2.0/log4j-api/apidocs/org/apache/logging/log4j/Marker.html
> Markers are objects that are used to add easily filterable information to log messages. Markers can be hierarchical - each Marker may have a parent. This allows for broad categories being subdivided into more specific categories. An example might be a Marker named "Error" with children named "SystemError" and "ApplicationError".

**Comment by EisenbergEffect** [comment]
Why not just use a function of your own specification:

```
AddressForm.LOG.debug(this.marker("Address form attached to DOM"));
```

You could even create your own overload that did this.
