### ISSUE TITLE
isLogLevel() missing

### ISSUE THREAD

**Issue by ZoolWay** [aurelia/logging#41]
**I'm submitting a feature request**

* **Library Version:**
aurelia-logging 1.3.0

* **Language:**
all

**Current behavior:**
You cannot check for the current log level. Because of this you cannot suppress calculations which would only be required in debug log level e.g.

**Expected/desired behavior:**
As most logging frameworks there should be methods to check the level like `isDebug()` or `isDebugEnabled()` or `isLogLevel(logLevel)`.

* **What is the motivation / use case for changing the behavior?**
Reducing performance hits for calculation not required for the current log level. Most commonly when a log level like `debug` should output all array contents or some calculated detail data just for logging purposes.

**Comment by Alexander-Taran** [comment]
@Deterus 'help_wanted' tag is there to signal: "we'd love a PR on this"

**Comment by EisenbergEffect** [comment]
Merged the isDebugEnabled code. Thanks again @Deterus  and apologies for the very long delay.
