### ISSUE TITLE
Add option to enable source location

### ISSUE THREAD

**Issue by unional** [aurelia/logging#44]
**I'm submitting a feature request**

* **Library Version:**
1.3.1

One feedback from the user of `aurelia-logging` is that we lose the ability to point to the source where the log is called. e.g.:
![image](https://cloud.githubusercontent.com/assets/3254987/25549967/1f206c06-2c2a-11e7-99ab-ef633506df80.png)
The source points to the appender where the actual `console.log()` is being called.

Can we introduce an option that will add the source location to the end of the message?
This way, at least in chrome and firefox, the browser will recognize that as a link and allow the user to click and jump to the source.

**Comment by EisenbergEffect** [comment]
If you know a way to make this work and can do it without breaking the api, please submit a PR and we'll gladly put it in.

**Comment by AStoker** [comment]
Is this still an issue? The stack that contains the line number where things are broken is included in the message to the logger. You can easily have a custom appender that puts that stack trace in the console (this is what we do now in our projects).

**Comment by AStoker** [comment]
Something like this works fine
``` javascript
debug(logger, message, ...rest) {
   console.debug(`DEBUG [${logger.id}] ${message.message} \n${message.stack}`, ...rest);
}
```

**Comment by AStoker** [comment]
@unional, let me know if that works for you. If it doesn't, I feel like we can get this behavior without having to make changes to the logger (gut is telling me that at least 😛 )

**Comment by unional** [comment]
How do you use it. Are you mandating the consumer to write `log.info({ message: 'abc', stack: ??? }, ...)`?

If that is so, then it is not a good solution.

**Comment by AStoker** [comment]
I apologize, in my setup I was actually logging an error object which contains the stack. But, that being said, you can still easily get the stack in the logger the same way. Something like this would accomplish what you're talking about
``` javascript
warn(logger, message, ...rest) {
        if (this.outputLevel >= LOG_LEVELS.WARN) {
            let stack = new Error().stack;
            console.warn(`WARN [${logger.id}] ${message} \n${stack}`, ...rest);
        }
}
...
log.warn('some message');
/* Output
ERROR [test] some message
 Error
    at eval (eval at error (https://localhost:44301/dist/app-bundle.js:6895:17), <anonymous>:1:14)
    at SystemLogAppender.error (https://localhost:44301/dist/app-bundle.js:6895:17)
    at Logger.error (https://localhost:44301/dist/aurelia-bundle.js:8258:46)
    at new SomeCustomClass (https://localhost:44301/dist/settings-bundle.js:7815:17)
    at Object.invokeWithDynamicDependencies (...
*/
```
Including the stack trace on every kind of log message would be too much info in the console I think. For example, in our production code, we only want stack traces logged for errors, we don't want stack traces logged for simple debug or info messages.   
Leaving that control/choice at the function level instead of the logging level seems to make more sense to me... But again, that's just me :)

**Comment by unional** [comment]
My approach in the PR is to get the first entry of the stack to avoid putting the whole stack there.

This reasoning for this issue is to show the line where the log happens, not the whole stack so that user can see immediately where the log happens.
e.g.:
![image](https://user-images.githubusercontent.com/3254987/29933594-0d5ca7e0-8e2d-11e7-8c8b-0466a7ba84c2.png)

That's why it should be there for all logLevel, not just error and warn.

**Comment by unional** [comment]
by the way, it should probably be:

```js
// pseudo!!
console.warn(`WARN [${logger.id}] ${message}`, ...rest, stack);
```
So that user still get what they expect while the stack is still available.

**Comment by AStoker** [comment]
Still, I think that listing the line number for every message would spam the console too much. There are potentially hundreds of debug and info messages that get thrown to the log on app start.  
Personally, I don't think that having the trace on every message (and the subsequent spamming) would buy the user anything. But again, this is just my opinion, and I've been known to be wrong a time or two.  
Could you provide some valid use cases for where the user would want to have the stack trace on something like an info message?

**Comment by krisdages** [comment]
If you are debugging in Chrome DevTools, you can blackbox the scripts from aurelia-logging, and the source location shown in the console will eventually be your own code, with source maps still respected.  I think it only takes a couple of iterations of blackboxing.

**Comment by unional** [comment]
> you can blackbox the scripts from aurelia-logging

Can you elaborate?



> line number for every message would spam the console too much

This is what all log message does in the DevTool. The purpose is allowing the engineer to click on the line which directs them to the source code.
That is why it is needed for every message.

This issue is about restoring that functionality because DevTools will show the Appender code where the actual `console.log` is being called, making the user not able to go to the code where the `logger.info|warn|debug()` being called.

> ...having the trace on every message

Since we are adding only the line at the end of the message, this is a good compromise.
Also, it can be turned off through options. Please check out the PR: #47

**Comment by AStoker** [comment]
I checked out the PR earlier. It's set up to enable logging per logger, you don't have the option to disable it once enabled (from what I can tell).  

I'm still trying to come to terms with a valid use case for this. You said that purpose was to allow the engineer to click on the line to direct them to the source code that called the log. Again I ask, would this be desired for every single type of logged message?   
Diving in, what is the purpose of an engineer clicking on a line to show them where the log was called? Predominantly, it's when something went wrong and they're trying to see where it went wrong, and how it went wrong. If they're diving in to see what went wrong, a stack trace is going to be helpful probably 75% of the time (in which case they'd want to add a stack trace to their logger anyway).  
Additionally, about 90% of your debug messages are probably going to be messages about Aurelia loading up resources and the like, in which case you don't really care about what line called what.  

Ultimately, what I'm trying to lead up to is that wanting stack traces is a very particular thing (you want them in particular use cases, maybe you don't want them enabled while in production, the variations can differ greatly per user).  
We can either modify the source logging code to provide a universal on-off switch per logger (your PR), or the user can specify with their own logger exactly how they want logging to work (they could make it work universally like your PR easily enough).  
My opinion (and it's just mine) is that having this kind of option in the logger is a bit superfluous.

**Comment by krisdages** [comment]
Sorry for the late response,

If the source line says "aurelia-logging.js" or any other file than your own source file, click it to open the file in the Sources panel, then right click anywhere in the source body. There should be an option that says "Blackbox script".  That will keep that script hidden in the stack panel and also make the source location line show the source as the next script in the stack that is not blackboxed.  I blackboxed aurelia-logging and aurelia-logging-console and now my source file shows up whenever I call logger.*( )

**Comment by EisenbergEffect** [comment]
Closing this since the blackbox option seems to be the best solution. Thanks @krisdages !
